#!/system/bin/sh
#Governor
#Change CPU governor:
#Lulzactiveq

/sbin/busybox mount -o rw,remount /
/sbin/busybox mount -o rw,remount /system

# Clearing existing selected relevant scripts
/sbin/busybox rm /system/etc/init.d/*001bkschedmcpowersavings*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandd*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandf*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandr*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandi*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandl*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandp*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemands*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandt*

chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "lulzactiveq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# Default values (also hard coded)
echo "80" > /sys/devices/system/cpu/cpufreq/lulzactiveq/inc_cpu_load 
echo "60" > /sys/devices/system/cpu/cpufreq/lulzactiveq/dec_cpu_load 
echo "2" > /sys/devices/system/cpu/cpufreq/lulzactiveq/pump_up_step 
echo "1" > /sys/devices/system/cpu/cpufreq/lulzactiveq/pump_down_step 
echo "40000" > /sys/devices/system/cpu/cpufreq/lulzactiveq/up_sample_time 
echo "20000" > /sys/devices/system/cpu/cpufreq/lulzactiveq/down_sample_time 
echo "13" > /sys/devices/system/cpu/cpufreq/lulzactiveq/screen_off_min_step
chmod 444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

