#!/system/bin/sh
#Governor
#Change CPU governor:
#Pegasusq - Boeffla (moderate)

/sbin/busybox mount -o rw,remount /
/sbin/busybox mount -o rw,remount /system

# Clearing existing selected relevant scripts
/sbin/busybox rm /system/etc/init.d/*001bkschedmcpowersavings*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandd*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandf*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandr*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandi*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandl*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandp*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemands*
/sbin/busybox rm /system/etc/init.d/*001bkfunctionondemandt*

# switch governor
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "pegasusq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
/sbin/busybox sleep 2

# cpu2 (500000/200000/100/100)
echo "800000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_1_1
echo "700000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_2_0
echo "100" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_1_1
echo "100" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_2_0

# cpu3  (500000/200000/200/200)
echo "1100000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_2_1
echo "1000000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_3_0
echo "300" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_2_1
echo "300" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_3_0

# cpu4  (500000/200000/300/300)
echo "1300000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_3_1
echo "1200000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_4_0
echo "400" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_3_1
echo "400" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_4_0

# 20
echo "10" > /sys/devices/system/cpu/cpufreq/pegasusq/cpu_down_rate

# 10
echo "10" > /sys/devices/system/cpu/cpufreq/pegasusq/cpu_up_rate

# 85
echo "85" > /sys/devices/system/cpu/cpufreq/pegasusq/up_threshold

# 37
echo "37" > /sys/devices/system/cpu/cpufreq/pegasusq/freq_step

chmod 444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

