#!/system/bin/sh
#Scheduler (ext SD)
#Change I/O scheduler for external SD memory:
#Noop

chmod 666 /sys/block/mmcblk1/queue/scheduler
echo "noop" > /sys/block/mmcblk1/queue/scheduler
chmod 444 /sys/block/mmcblk1/queue/scheduler

