#!/system/bin/sh
#LED fading
#Notification LED fading
#Blink (normal, stock)

echo "0" > /sys/class/sec/led/led_fade

if [ "`uname -r | grep AOSP`" ];
	then
	#CM mode
	echo "0" > /sys/class/sec/led/led_intensity
	else
	#SAMSUNG mode
	echo "40" > /sys/class/sec/led/led_intensity
fi

