#!/sbin/busybox sh
#Touch Wake
#Enable or disable Touch to Wake:
#15 sec

echo "1" > /sys/class/misc/touchwakee/tw_enabled
echo "15" > /sys/class/misc/touchwakee/tw_delay
echo "0" > /sys/class/misc/touchwakee/tw_charger_mode

