#!/sbin/busybox sh
#LZ4 ZRAM SIZE
#Set Max Total Size (MB):
#400 MB

#Zram0
swapoff /dev/block/zram0
echo 1 > /sys/block/zram0/reset
echo 419430400 > /sys/block/zram0/disksize
echo 1 > /sys/block/zram0/initstate
mkswap /dev/block/zram0
swapon -p 2 /dev/block/zram0

